### ISSUE TITLE
Need to be clear about brand colors

### ISSUE THREAD

**Issue by doyourbest96** [BlueOcean5911/ai-vio-backend#3]
There are too many pages and each page has a different brand color.
We need to fix this and before that we need to figure out how to set the default.

Please leave clear examples for buttons and table rows (background color, border color, hover color, etc.)

**Comment by BlueOcean5911** [comment]
Yeah, right.
button color - blue-500
button hover - color - blue-100 or blue-50
row color for table - even - blue-50, odd - white
hover row color for table - gray-50

This is basic Color Planet. We can discuss others. Thanks

**Comment by doyourbest96** [comment]
And then the button secondary color?

**Comment by doyourbest96** [comment]
Thanks.

**Comment by BlueOcean5911** [comment]
### secondary color
background gray-300
hover color gray-200

**Comment by doyourbest96** [comment]
Thank you for your kind guide.

**Comment by doyourbest96** [comment]
I think this is not good.

**Comment by BlueOcean5911** [comment]
### Primary color
background color - blue-500
hover color - blue-400

### Secondary Button color
background color - gray-300
hover color - gray-200

Please let me know your opinion

**Comment by doyourbest96** [comment]
After I test it, I will let you know.
Thank you.

**Comment by doyourbest96** [comment]
Looks good.
